name: "Request a documentation"
description: "Request a documentation"
labels: [documentation]
body:
- id: documentation
  type: textarea
  attributes:
    label: "Documentation"
  validations:
    required: true