name: "Request a documentation"
description: "Request a documentation"
labels: [documentation]
body:
- id: documentation
  type: textarea
  attributes:
    label: "Documentation"
    placeholder: "Explain the documentation you want to request"
  validations:
    required: true